package com.example;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * This class represents the Country entity.
 * It is mapped to a database table using JPA annotations.
 */
@Entity
public class Country {
	@Id // Marks the `id` field as the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    // Configures the primary key to be auto-generated by the database.
    private Long id;
    private String name;
    private Long population;

    // Getters and Setters
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public Long getPopulation() {
        return population;
    }
    public void setPopulation(Long population) {
        this.population = population;
    }
	public Country(Long id, String name, Long population) {
		super();
		this.id = id;
		this.name = name;
		this.population = population;
	}
	public Country() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}
